### ISSUE TITLE
How to send response from server

### ISSUE THREAD

**Issue by joflo5712** [kpavlov/jreactive-8583#1]
I have created a Client and Server class as prescribed by the example code.  I am generating Iso messages in the client that are being received by the server, which are being passed to its onMessage handler. I have used the createResponse(arg1) method of the messageFactory to create a response.  Could you please let me know what object/method is used to return this response to the client?

**Comment by joflo5712** [comment]
OK.  I see that the ctx argument in the onMessage() handler provides the method: writeAndFlush() to send the response.  Thx

**Comment by kpavlov** [comment]
Exactly!
