### ISSUE TITLE
Question about MessageFactory

### ISSUE THREAD

**Issue by genuss** [kpavlov/jreactive-8583#111]
First, thanks for a great addition to good-old j8583. You library makes j8583 much more usable.
I v1.2.0 you introduced `com.github.kpavlov.jreactive8583.iso.MessageFactory` which delegates some calls to `com.solab.iso8583.MessageFactory` and adds one method `newMessage(MessageClass, MessageFunction, MessageOrigin)`. I guess you wanted to hide all methods which change state of the `MessageFactory`, didn't you?
The question is: what's the point of hiding some methods of original class? I'd like to use other methods in that class but with 1.2.0 it's not possible anymore. What do you think about adding some additional methods to your interface? Personally I'm interested in newly added `createResponse(T, boolean)`, but it may be possible to add some more.

**Comment by kpavlov** [comment]
The reason for introducing MessageFactory is to support multiple ISO versions. There was no intention to hide useful underlaying methods
