### ISSUE TITLE
java.text.ParseException: ISO8583 MessageFactory has no parsing guide for message  when header is sent in iso request

### ISSUE THREAD

**Issue by MyBhasi** [kpavlov/jreactive-8583#116]
Caused by: java.text.ParseException: ISO8583 MessageFactory has no parsing guide for message type 1b3f0

**Comment by kpavlov** [comment]
Isn't it a limitation of j8583 library?

**Comment by danicaliforrnia** [comment]
does this have a solution?. I'm getting the same error using a header specify in my j8583.xml file.

**Comment by MyBhasi** [comment]
had to do with other way around . Created socket connection and used MessageFactory  method parseMessage  where u can send array of bytes from input stream and header length.
