### ISSUE TITLE
How to instantiate a J8583MessageFactory?

### ISSUE THREAD

**Issue by birnbuazn** [kpavlov/jreactive-8583#120]
Hi Pavlov,

First of all. Thanks for the great work. I'm having an issue when trying to instantiate a `J8583MessageFactory`, though. This class is marked as `internal`, giving me a warning (in Java) when I try to new-up the factory like stated in the documentation (and in your test-cases).

What's the preferred way of creating a `J8583MessageFactory`?

Stefan

**Comment by kpavlov** [comment]
Hi, Stefan. It was made internal by mistake, it should be public. Please, ignore this warning.

**Comment by vitaly-zhuravlyov** [comment]
Hi Konstantin,

That internal declaration may work in Java but it doesn't in Kotlin. Do you have any ETA for a fix?

Thanks
Vitaly

**Comment by kpavlov** [comment]
ETA is as soon as build pass
