### ISSUE TITLE
No parsing guide for 8020, 8030, 8040... message types

### ISSUE THREAD

**Issue by danicaliforrnia** [kpavlov/jreactive-8583#125]
Hi Pavlov,

I'm getting an exception after 8010 response message as follow:

`java.text.ParseException: ISO8583 MessageFactory has no parsing guide for message type 0820 [082082200000020000000400000000000000030118024102512900301]`

If I add a 0820 template in the j8583.xml file then the same exception is thrown but for 0830, then, as you add more message type templates, the error is thrown again but for 08XX where XX is the last template in the xml file plus 10 (0840, 0850, ...).

What could be causing this issue?

**Comment by kpavlov** [comment]
Hi,
I would suggest trying to test parsing guide against the j8583 library. My library does not deal with message parsing, it's responsibility of the MessageFactory

**Comment by danicaliforrnia** [comment]
Thanks for your answer,

but do you know why is 0820 message generated after 0810 response?

**Comment by kpavlov** [comment]
What are those messages? Echos?

**Comment by danicaliforrnia** [comment]
Yes, they are.

**Comment by danicaliforrnia** [comment]
Also, I'm not able to use headers in my ISO messages. j8583 MessageFactory receives 0 as the iso header length causing an ParseException.

**Comment by danicaliforrnia** [comment]
The problem seems to be with the `Iso8583Decoder ` wich passes 0 as the isoHeaderLength need it in the `MessageFactory`, because of that the ParseException is thrown.

**Comment by pandans** [comment]
> The problem seems to be with the `Iso8583Decoder` wich passes 0 as the isoHeaderLength need it in the `MessageFactory`, because of that the ParseException is thrown.

has found any ways to slove it ?

**Comment by danicaliforrnia** [comment]
> > The problem seems to be with the `Iso8583Decoder` wich passes 0 as the isoHeaderLength need it in the `MessageFactory`, because of that the ParseException is thrown.
> 
> has found any ways to slove it ?

I created a `CustomMessageFactory` class inheriting from `MessageFactory` where I pass the isoHeaderLength param in the parse method and implement this `CustomMessageFactory` in the client/server configuration.
