### ISSUE TITLE
Long idle timout

### ISSUE THREAD

**Issue by danicaliforrnia** [kpavlov/jreactive-8583#127]
Hi,

I'm trying to implement a echo message rate of 120 seconds, but it seems that the connection breaks or is lost when the idleTimeout is set above 30 seconds.

how can I handle this?

**Comment by kpavlov** [comment]
It is [ReadTimeoutHandler](https://netty.io/4.0/api/io/netty/handler/timeout/ReadTimeoutHandler.html) closes the connection.

**Comment by kpavlov** [comment]
Try setting [idleTimeout](https://github.com/kpavlov/jreactive-8583/blob/master/src/main/kotlin/com/github/kpavlov/jreactive8583/netty/pipeline/Iso8583ChannelInitializer.kt#L68) in the configuration to something less than 30 sec and make sure that echo message listener is enabled.
