### ISSUE TITLE
Iso8583Client not receiving/replying 0x800 messages

### ISSUE THREAD

**Issue by eraad** [kpavlov/jreactive-8583#19]
Hi, I'm connecting an `Iso8583Client` to a host that is supposed to be sending `0x800` messages. I have implemented the following Clojure code but for some reason the listener is not triggered. I have no evidence that the `0x800` messages are being received.

Please note that I'm able to receive responses such as `0x210` with the same implementation style.

Does the `withEchoMessageListener` setting available in the `ClientConfiguration` class have anything to do? I'm not using it at all.

```clojure
(def mti-0800 (reify IsoMessageListener
               (applies [this iso-msg]
                 (= (.getType iso-msg) 0x800))
                (onMessage [this ctx iso-msg]
                  (println (.debugString iso-msg))
                  (let [f (msg-factory "bp/res.xml")
                        resp (.createResponse msg-factory iso-msg)]
                    (do
                      (.setField resp 39 (.value IsoType/ALPHA "00" 2))
                      (.writeAndFlush ctx resp)
                      false)))))

(defn client
  [msg-factory host port]
  (let [socket (new InetSocketAddress host port)
        conf (.build (ClientConfiguration/newBuilder))
        new-client (new Iso8583Client socket conf msg-factory)]
    (doto new-client
      (.addMessageListener mti-0210)
      (.addMessageListener mti-0410)
      (.addMessageListener mti-0800)
      (.addMessageListener mti-0810))))
```

Thanks!

**Comment by kpavlov** [comment]
Hi Eduardo
I think you may want to use `org.jreactive.iso8583.ConnectorConfiguration.Builder.withAddLoggingHandler(true)` to setup logging handler. EchoMessageListener does nothing but replies to the message received, but you need to trace messages and continue processing.
Note also `ConnectorConfiguration.Builder.withLogSensitiveData(false)' to prevent logging PAN & CVVs. See `org.jreactive.iso8583.netty.pipeline.IsoMessageLoggingHandler`

**Comment by eraad** [comment]
Got it @kpavlov. The host was sending the `0x800` messages to the wrong port. Anyways, I got a good insight on how to configure the client so thanks!

Eduardo
