### ISSUE TITLE
How to handle Response from server?

### ISSUE THREAD

**Issue by keyhan** [kpavlov/jreactive-8583#2]
Hello, I was thinking of using jreactive, and I have looked at the code and your example a little. I was wondering when setting up the client and sending the request, how do you handle the result?

In the simple example in your page you just send a request and close the socket, which is not how you want to do IRL. You want to read and parse the answer.

Regards

**Comment by keyhan** [comment]
I think I just saw my answer. Thanks for the tool, looking forward in trying it out.

**Comment by dagnetro** [comment]
Hello,

I don't get it how to handle response from server.

	
            MessageFactory msga;

            IsoMessage msg = msga.newMessage(0x200);

            msg.setField(2, IsoType.LLVAR.value("4256737383838383", 16));
            msg.setField(3, IsoType.NUMERIC.value(000000, 6));

            client.send(msg);

            // Here i want to get from response field with no. 39, response code field.

            client.shutdown();

How you solve this, i have put j8583.xml in resources, and it's configured for type 0210, can you help me with this?

PS: @kpavlov , thank you for jreactive-8583. 👍
