### ISSUE TITLE
ReconnectOnCloseListener.java line 49 problem The method schedule(Runnable, long, TimeUnit) is ambiguous for the type ScheduledExecutorService

### ISSUE THREAD

**Issue by SteelCodeEdgarGaribay** [kpavlov/jreactive-8583#26]
ReconnectOnCloseListener.java line 49 problem The method schedule(Runnable, long, TimeUnit) is ambiguous for the type ScheduledExecutorService

**Comment by jamalzkhan** [comment]
Getting the same error

**Comment by mrtechit** [comment]
Ya, even i am getting the same error

**Comment by omarnacis** [comment]
Hello everyone a have the same error

**Comment by honeyzzang** [comment]
excutorService.schedule( () -> client.connectAsync(), reconnectInterval, TimeUnit.MILLSECONDS);
