### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pancho100e** [kpavlov/jreactive-8583#27]
Hi congratulation for the great iniciative.
I am trying to run a basic example client and server But I could not do it..
The querstion is: 
is it possible for us to share a basic example ( compilable)  to then thoroughly study this great software?

thanks you

**Comment by kpavlov** [comment]
Thank you, @pancho100e 
It worth adding some example project.
Meanwhile, you may have a look at integration tests:

- [AbstractIT.java](https://github.com/kpavlov/jreactive-8583/blob/master/src/test/java/com/github/kpavlov/jreactive8583/example/AbstractIT.java) -- here the server and client are started
- [ClientServerIT](https://github.com/kpavlov/jreactive-8583/blob/master/src/test/java/com/github/kpavlov/jreactive8583/example/ClientServerIT.java) -- echo server using the client example
