### ISSUE TITLE
Does it support multiplexing client IO ?

### ISSUE THREAD

**Issue by mrtechit** [kpavlov/jreactive-8583#34]
Hi,
I have been looking at this API for some time now.
Can we multithread the client to accept multiple asynchronous message and in turn have a multiplexed IO running ?
I am not able to get around that how will we use the "addMessageListener" method to map the correct request to the response received. (As it could be that response for second request come before the response of first request).

**Comment by kpavlov** [comment]
Hi @mrtechit 
Sorry for delay.
If you want that response-to-request mapping you may want to use correlation ID in your messages and `CompletableFuture`s. E.g. 
1. Put `CompletableFuture` to the map using correlation ID as a key.
2. When you receive message - [remove](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#remove-java.lang.Object-) matching `CompletableFuture` from a map by correlation ID and complete a Future, if it was present in a map.

**Comment by mrtechit** [comment]
Hi,
Sorry i think my question was not clear.
Mapping request to response is not problem.
Issue is that the client accepts the response of messages 1 by 1.
The pipeline works in blocking manner only with CLIENT.

PS : The server works fine

**Comment by kpavlov** [comment]
Maybe, custom channel handler in client pipeline could bring this functionality?

**Comment by mrtechit** [comment]
Custom channel will also get blocked as the message listener is single threaded per client instance.
