### ISSUE TITLE
How to send a message by the server outside listener?

### ISSUE THREAD

**Issue by ouadi** [kpavlov/jreactive-8583#36]
I'm developing an ISO8583 simulator based on your framework `jreactive-8583`. The simulator acts as an `Iso8583Server`. It also has REST interface:

1. `Iso8583Client`s will connect to the simulator and send to it `IsoMessage`s. The server will reply to this requests from within the corresponding `IsoMessageListener<IsoMessage>`.
1. The simulator accepts requests from its REST interface that it convert to `IsoMessage`s and need to forward these messages to the corresponding `Iso8583Client`.

I have implemented the first feature (receiving requests from clients and sending back replies). However, I'm stuck to implement the second feature (forwarding requests to a connected clients).

How can I get hand on the Channel/ChannelHandlerContext of connected clients?

I have reviewed all examples, read all issues (#5 for instance) and went through the source code. I can see a way to that.

**Comment by kpavlov** [comment]
Hello @ouadi 
You may want to register a Channel in a thread-safe map with a under key which is your client identifier. Later on, you may get a channel from map by client ID and send a message to this channel. You should remove a channel from map on disconnect.

**Comment by ouadi** [comment]
Hello @kpavlov 

Thank you for the quick answer.

Yes, you are right. I have to keep track of connected clients using some sort of identifiers and use that to send messages from the server to appropriate client as needed (that is the case as each client that opens a connection should immediately sends a sign-on request with its identifier).

My issue is not at this level. My issue is to get hand on the channel allocated at the server level to each client so that I can send messages to it.

Can you please share a direction to achieve that?

_Note: I have no experience with `netty` framework. That may explain question._

**Comment by ouadi** [comment]
Thank you for the quick reply.

Is there a way to get notified each time a client connects to the server?

**Comment by kpavlov** [comment]
@ouadi, you should use 2 methods: `[ChannelInboundHandler.channelActive(...)](https://netty.io/4.1/api/io/netty/channel/ChannelInboundHandler.html#channelActive-io.netty.channel.ChannelHandlerContext-)` and `ChannelInboundHandler.channelInactive(...)`
You may extend you handler from `ChannelInboundHandlerAdapter`
