### ISSUE TITLE
Iso8583 Decoder issue while data is in EBCDIC format

### ISSUE THREAD

**Issue by Kurukshetran** [kpavlov/jreactive-8583#43]
Iso8583 Decoder is not decoding ebcdic formatted message.
Here is the sample data
{1, 14, -16, -15, -16, -16, 126, -1, 68, 1, 8, -31, -32, 10, -15, -10, -11, -14, -16, -12, -9, -13, -16, -16, -16, -16, -16, -16, -16, -16, -15, -13, -15, -9, -16, -16, -16, -16, -16, -16, -16, -16, -16, -16, -16, -15, -16, -16, -16, -16, -16, -16, -16, -16, -16, -16, -16, -15, -16, -16, -16, -16, -16, -16, -16, -16, -16, -16, -16, -15, -16, -16, -16, -16, -16, -13, -16, -14, -15, -13, -11, -16, -11, -10, -10, -15, -16, -16, -16, -16, -16, -16, -10, -15, -16, -16, -16, -16, -16, -16, -16, -16, -16, -16, -16, -14, -15, -13, -11, -16, -11, -10, -16, -13, -16, -14, -15, -8, -15, -14, -16, -13, -16, -14, -16, -13, -16, -14, -10, -16, -15, -16, -16, -15, -14, -16, -10, -7, -7, -7, -7, -16, -15, -16, -8, -16, -16, -16, -16, -16, -16, -16, -16, -16, -15, -44, -29, -58, 64, -29, -59, -30, -29, -63, -62, -61, -15, -14, -13, -29, -59, -30, -29, -44, -29, -58, -15, -7, -44, -123, -108, -126, -123, -103, 64, -58, -119, -107, -127, -107, -125, -119, -127, -109, 64, -55, -107, -94, -93, -119, 64, -44, -127, -107, -125, -120, -123, -94, -93, -123, -103, 64, 64, 64, 64, -44, -42, 64, -16, -16, -15, -61, -8, -12, -16, -8, -12, -16, -8, -12, -16, -16, -14, -10, -16, -16, -15, -16, -16, -15, -16, -16, -16, -16, -14, -16, -16, -8, -12, -16, -15, -14, -13, -12, -11, 96, -10, -9, -8, -7, -16, -16, -7, -44, -61, -30, -16, -15, -15, -16, -25, -41}

**Comment by kpavlov** [comment]
I believe it's j8583 library issue
