### ISSUE TITLE
How can I start jreactive-8583 server in the SpringBoot application?

### ISSUE THREAD

**Issue by trongtran-agilityio** [kpavlov/jreactive-8583#45]
I am thinking that I need to start Iso8583Server at MainApplication.java file and define a MyController.java to register all incoming listening (server.addMessageListener ....).

Also how can I stop Tomcat server from SpringBoot?

**Comment by kpavlov** [comment]
You don’t need an mvc controlling under netty, you have to register
handlers to react on messages. If you will not include
spring-boot-starter-tomcat dependency then you will have no tomcat to stop
;)
