### ISSUE TITLE
How can I stop to send 0x800 msg to the server

### ISSUE THREAD

**Issue by r3nan** [kpavlov/jreactive-8583#46]
The server that Im trying to connect can receive a limited messages, and I spending all these slots with message 0x800 that Im not found where I can handle it (the schedule or where i can prevent it sending).

Is it possible to prevent 0x800 sendings from the client to the server?

**Comment by r3nan** [comment]
Using the method "withIdleTimeout()" I could delayed the messages, but the connection break every time.

**Comment by kpavlov** [comment]
Hi @r3nan 
You should not add `EchoMessageListener` to `CompositeMessageHandler`. Please check `ConnectorConfiguration.shouldAddEchoMessageListener()`.
