### ISSUE TITLE
Modifying 0x0800 Network Management

### ISSUE THREAD

**Issue by adityariyadi** [kpavlov/jreactive-8583#47]
Hi, I am able to run it on Spring Boot and it works fine. Great stuff. But I am trying to modify the 0x0800 message which automatically sent over between client and server using data from j8583.xml file and I  want  to add data element 7 for current date time. How to do that? I try to find out where is the method that generate this message and couldn't find it anywhere. I am just wondering if you could give some insight. I appreciate your great codes. Thanks!.

**Comment by adityariyadi** [comment]
@kpavlov Thanks, I have customized 0x0800 Network Management message. 

I made client and server using JReactive and simulate processes between client and server and every single step goes fine. 

But now I stumbled into another problem. When I change the server to another 'real' production iso server, it doesn't work. Client to server connection goes well. But when I tried to sign on with 0x0800 message, server simply rejecting it and connection suddenly drop. 

ReconnectOnCloseListener says  Client connection was closed to ...[ip address of server]..
and
IsiMessageLoggingHandler says  EXCEPTION: java.io.IOException: Connection reset by peer

The server expecting message in ASCII format with 4 digit header containing information of message length (not including this header).

What I am suspecting is the message format is not conforming with server is expecting, like the header or may be bitmap either in binary or not. Do you have any idea what may cause the difference between JReactive server and the 'real' production server? 

BTW, the server receiving garbled message and wrong header and MTI. Thank you for giving me some advice.

**Comment by kpavlov** [comment]
Hi
Please try to customize MessageFactory

Best regards,
Konstantin

**Comment by kpavlov** [comment]
Any test with real test data would be highly appreciated 

Best regards,
Konstantin

**Comment by adityariyadi** [comment]
Hi,

Now client is able to send message through server without EXCEPTION: java.io.IOException: Connection reset by peer.  I modifying message header at Iso8583Encoder.java and message now is readable at the server. But client do not received 0x0810 reply. I try to debug at the Iso8583Decoder.java, but it seems message never reach that part. But very strange, there is no exception thrown. Do you have any suggestion?

Thank you very much.

**Comment by kpavlov** [comment]
Try to debug at frame decoder

Best regards,
Konstantin

**Comment by adityariyadi** [comment]
Hi,
I try to debug at Iso8583Decoder which extends ByteToMessageDecoder , it seems never reach that point. How ever I got message from IsoMessageLoggingHandler  : [id: 0x370d169a, L:/{myIP:Port} - R:/{serverIP:port}] READ COMPLETE.

But listeners never fired. Do you have any idea? Thank you.

**Comment by kpavlov** [comment]
Looks like `LengthFieldBasedFrameDecoder` is dropping the connection because of too long frame. There may be something wrong with frame length field in the message.
Please check `ConnectorConfiguration#frameLengthFieldLength` field.
