### ISSUE TITLE
In the server, how do you reply?

### ISSUE THREAD

**Issue by keyhan** [kpavlov/jreactive-8583#5]
Hi, I was thinking of setting up a server, I looked at your example and the code, I cannot find an easy way to answer to a client. Client class has a send method, but there are no send method in the server class. Am I missing something obvious?

regards
Keyhan

**Comment by kpavlov** [comment]
Hello, @Keyhan

Server is asynchronous by nature. You should create and register a message listener which will do the job, e.g.:
```java
server.addMessageListener(new IsoMessageListener<IsoMessage>() {

            @Override
            public boolean applies(IsoMessage isoMessage) {
                return isoMessage.getType() ==  0x200;
            }

            @Override
            public boolean onMessage(ChannelHandlerContext ctx, IsoMessage isoMessage) {
                capturedRequest = isoMessage;
                final IsoMessage response = server.getIsoMessageFactory().createResponse(isoMessage);
                response.setField(39, IsoType.ALPHA.value("00", 2));
                response.setField(60, IsoType.LLLVAR.value("XXX", 3));
                ctx.writeAndFlush(response);
                return false;
            }
        });
```
In general, you can send a message to client via Netty's `[ChannelHandlerContext](http://netty.io/4.1/api/io/netty/channel/ChannelHandlerContext.html)`.

**Comment by keyhan** [comment]
Thanks, I think a better way would be to move sendasync up to the connector
class so it could be used both by client and server.
Den 6 feb 2016 23:17 skrev "Konstantin Pavlov" <notifications@github.com>:

**Comment by kpavlov** [comment]
> I think a better way would be to move sendasync up to the connector class so it could be used both by client and server.

No, you need to know a `Channel`/`ChannelHandlerContext` to send to if you want to have simple method like `sendAsync(message)`.
On the client you have the only one `Channel`, while on server there are many channels. Once you know a channel on server (e.g. you may want to create a repository of opened client's `ChannelHandlerContext`), you can use it's `write(...)` method.

**Comment by keyhan** [comment]
Ok thanx for clarification

lör 6 feb. 2016 kl. 23:51 skrev Konstantin Pavlov <notifications@github.com
