### ISSUE TITLE
Question: How i get response from server and verify

### ISSUE THREAD

**Issue by dagnetro** [kpavlov/jreactive-8583#53]
I have a simple client method to call a ISO8583, i call and it's working, the message get to server, it's posted (i have configured the j8583.xml in resources for 0210 msg format), but how i get the response, i want to verify the response code(field 39) is '00' for example, can you help me with that?

Something like:

response.getField(39);

```
public static void callISO(IsoMessage isoMessage) throws Exception {

        MessageFactory<IsoMessage> messageFactory = ConfigParser.createDefault();
        SocketAddress socketAddress = new InetSocketAddress(host, port);
        Iso8583Client<IsoMessage> client = new Iso8583Client<>(socketAddress, messageFactory);
        client.getConfiguration().replyOnError();
        client.init();
        client.connectAsync().sync();
        client.send(isoMessage);

**// HOW i get the response from server here?** 

       client.disconnectAsync();
        client.shutdown();


}
```

**Comment by kpavlov** [comment]
Sorry for late response.
You have to implement your own `com.github.kpavlov.jreactive8583.IsoMessageListener`, implement that logic in `onMessage` method and register your message listener in pipeline.
See `com.github.kpavlov.jreactive8583.example.ClientServerIT` as an example.
