### ISSUE TITLE
Unable to Test ClientServerIT 

### ISSUE THREAD

**Issue by Shahnawaz-bhurt** [kpavlov/jreactive-8583#54]
Getting Below Exception while Testing ClientServerIT Class
>  java.lang.Error: Unresolved compilation problem: 
> The method schedule(Runnable, long, TimeUnit) is ambiguous for the type ScheduledExecutorService

**Comment by kpavlov** [comment]
Can't reproduce. I'm using IntelliJ IDEA and openjdk-11.0.1.
The build is green: https://travis-ci.org/kpavlov/jreactive-8583
It is built under:
 - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11

Try to build it with maven:

    mvn clean verify
