### ISSUE TITLE
Getting ParseExceptionHandler is not a @Sharable handler, so can't be added or removed multiple times. When stopping and reconnecting client.

### ISSUE THREAD

**Issue by betocba** [kpavlov/jreactive-8583#61]
First of all, good work on putting `jreactive` together.
I am getting `io.netty.channel.ChannelPipelineException: com.github.kpavlov.jreactive8583.netty.pipeline.ParseExceptionHandler is not a @Sharable handler, so can't be added or removed multiple times.` exception every time I stop my client, restart it and try to send a message again.
My server initialization code is (Kotlin)

```java
        val messageFactory = ConfigParser.createDefault()
        val configuration = ServerConfiguration.newBuilder()
            .replyOnError(true)
            .build()

        server = Iso8583Server<IsoMessage>(port, configuration, messageFactory)
        server.init()
        server.start()
```
My understanding is that `CompositeIsoMessageHandler` IS "@Sharable" and this is the handler by default. What am I missing?.

**Comment by kpavlov** [comment]
Thank you @betocba
You’re right. It make sense to make this handler ‘@shareable’. PR is welcome

**Comment by betocba** [comment]
Thanks for your response @kpavlov. Here is the PR: https://github.com/kpavlov/jreactive-8583/pull/62
