### ISSUE TITLE
Error: Default interface methods are only supported starting with Android N (--min-api 24): void com.github.kpavlov.jreactive8583.ConnectorConfigurer.configureBootstrap(io.netty.bootstrap.AbstractBootstrap, com.github.kpavlov.jreactive8583.ConnectorConfiguration)

### ISSUE THREAD

**Issue by SunnyBe** [kpavlov/jreactive-8583#63]
I have a project that focuses on users with android min api of 21.  I found out that when I build and run my project with my parameter at min SDK 21 I get this file error com.github.kpavlov.jreactive8583.ConnectorConfigurer.configureBootstrap(io.netty.bootstrap.AbstractBootstrap, com.github.kpavlov.jreactive8583.ConnectorConfiguration). Can please Is there another way to resolve this?

**Comment by kpavlov** [comment]
Hello
I would suggest to try to build the library from sources targeting you JDK version. By default it is compiled for JDK 1.8
