### ISSUE TITLE
How can we implement server message listener to decrypt message?

### ISSUE THREAD

**Issue by Nzsquall** [kpavlov/jreactive-8583#64]
Hi,

Looking at _ClientServerIT_ test I know we can implement message listeners at server side to dispatch ISO response.

If the message sent by the application under test is encrypted ISO messages, is there a way we can implement the decryption logic in the message listener, before we dispatch the response accordingly? 

Thanks

**Comment by kpavlov** [comment]
Hello
We can implement decoding in a separate listener and add it to netty pipeline after iso message decoder
