### ISSUE TITLE
can i use this in android client?

### ISSUE THREAD

**Issue by dariushgh** [kpavlov/jreactive-8583#66]
if i can use please show me example of creating message with header and message length by 4 byte.
thanks

**Comment by kpavlov** [comment]
@dariushgh, did you mean frame length field? Than try this:

    ServerConfiguration.newBuilder().frameLengthFieldLength(4).xxx.build();

**Comment by dariushgh** [comment]
thanks for your answer,
do you have any document to implement your client library in my android app?
add jar file, then how to build message,pack and unpack message

**Comment by kpavlov** [comment]
Encoding and decoding is handled by [j8583](https://bitbucket.org/chochos/j8583/) library. Please check their documentation.

**Comment by dariushgh** [comment]
this link just is java code and have not any document or guide to implementation,can you help me?

**Comment by kpavlov** [comment]
I’m gonna to migrate the library to kotlin, so running on android will be easier
