### ISSUE TITLE
How to disable automatic echo message sent from client

### ISSUE THREAD

**Issue by Nzsquall** [kpavlov/jreactive-8583#68]
Hi @kpavlov,

How can I disable client from automatically sending echo messages?

I can see from the builder class that I can call addEchoMessageListener(), but I believe that is for handling server echo request.

In my client j8583.xml I have not defined any parser or template for echo request.

Not sure where this is generated from.

Any idea will be appreciated.

Thanks
Eric

**Comment by kpavlov** [comment]
`com.github.kpavlov.jreactive8583.netty.pipeline.EchoMessageListener` is responsible for it.
It should not be enabled by default but anyway you can switch it off: `com.github.kpavlov.jreactive8583.ConnectorConfiguration.Builder.withEchoMessageListener(false)`

**Comment by hamidsafdari** [comment]
Dear @kpavlov,

Unfortunately, setting that item in configuration doesn't really do much. I found out that it's actually IdleEventHandler that triggers sending an echo message so I check for `.shouldAddEchoMessageListener()` and disable IdleEventHandler if echo messages are not enabled.

The thing for me is that in my message format, echo message types are `0x1804` and `0x1814` and I have no way of overriding the default echo message handler.

I've already made a pull request #130 . I'd appreciate it if you could check it out and maybe merge it.
