### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by Carmy85** [kpavlov/jreactive-8583#71]
Hi @kpavlov,
It's possible to add a custom field to an ISOMessage?

for example, add to field 63 the following:

BIT     Data element    length      type
63.1    Service level      1              ASCII
63.3     Product code    3             Numeric

Thanks,
Carmelo.

**Comment by kpavlov** [comment]
Yes, you can put your own field definition file to classpath, like this one: src/test/resources/j8583.xml

See the reference here: http://j8583.sourceforge.net/xmlconf.html
