### ISSUE TITLE
iso8583Decoder does not support messages which have length in first 4 bytes

### ISSUE THREAD

**Issue by Vostan** [kpavlov/jreactive-8583#83]
I found this issue quite wired to not be able at least configure, I am ready to do a PR for this.

In some cases, there is a need to Decode/Encode messages which are starting with Iso Message length in the first 4 bytes e.g. JPOS sends/receives messages in this way.

In MessageFactory, if it is not with binaryheader currently we just read the first 4 bytes as a MTI.

```
type = ((buf[isoHeaderLength] - 48) << 12)
                    | ((buf[isoHeaderLength + 1] - 48) << 8)
                    | ((buf[isoHeaderLength + 2] - 48) << 4)
                    | (buf[isoHeaderLength + 3] - 48);
```

Currently, I have a workaround, I overwrite iso8583Decoder and iso8583Encoder

in Decoder I just read first 4 bytes` byteBuf.readBytes(4);`
in Encoder, I just add length in first 4 bytes 
```
byte[] bytes = isoMessage.writeData();
    //pad length with 0s
    byte[] lengthInBytes = ByteBuffer.allocate(4).put(String.format("%04d", bytes.length).getBytes()).array();
    int aLen = lengthInBytes.length;
    int bLen = bytes.length;
    byte[] bytesReadyToSend = new byte[aLen + bLen];
    System.arraycopy(lengthInBytes, 0, bytesReadyToSend, 0, aLen);
    System.arraycopy(bytes, 0, bytesReadyToSend, aLen, bLen);
    out.writeBytes(bytesReadyToSend);
```

P.S. I know that this is more of the issue to J8583, however, I thought that we could encapsulate this feature.

**Comment by solnaranu** [comment]
Hi @Vostan,

perhaps we had a similar problem. I created a [PR](https://github.com/kpavlov/jreactive-8583/pull/84) to help with it, we'll see how @kpavlov will respond. If you wish, you can try my fork and see if it helps you.

**Comment by kpavlov** [comment]
Test needed

**Comment by solnaranu** [comment]
> Test needed

Added in #88, please review.

**Comment by Vostan** [comment]
Hi @solnaranu, Thanks for this PR. Sure some people will use it.
