### ISSUE TITLE
Iso8583Decoder decode method issue

### ISSUE THREAD

**Issue by AmirHooshangi** [kpavlov/jreactive-8583#9]
Hi
in the decode method you just check:
 if (!byteBuf.isReadable()) {
            return;
        }
since TCP packets may come in a chunked base manner, some parts of your IsoMessage bytes may come in the next read. Shouldn't we say something like this :
IsomessageLength = first 4 bytes in the packet
 if (IsomessageLength <  byteBuf.readableBytes()) {
            return;
        }
Have you ever done StressTest this code ? i think it would clear my point.

**Comment by kpavlov** [comment]
Hi, thanks for the issue. I didn't do a stress test yet. The fix you're suggesting looks reasonable. Please submit pull request or I'll fix it a bit later.

**Comment by AmirHooshangi** [comment]
Sure, if i wrote the patch I'll do PR.

**Comment by kpavlov** [comment]
BTW, there is a pipeline handler responsible for aggregated splitted frames:
```
pipeline.addLast("lengthFieldFameDecoder", new LengthFieldBasedFrameDecoder(
configuration.getMaxFrameLength(), 0, headerLength, 0, headerLength));
```
It is configured in [Iso8583ChannelInitializer](https://github.com/kpavlov/jreactive-8583/blob/master/src/main/java/org/jreactive/iso8583/netty/pipeline/Iso8583ChannelInitializer.java)

It needs to write a stress test anyway to prove then everything works as expected.

**Comment by AmirHooshangi** [comment]
I've wrote a simple ByteToMessage decoder which is based on calculating message length from the first 4 bytes and it works fine  under 100 request, but starts to misbehave after that, i think it's due to the ByteBuf reader index.
I'll check LengthFieldBasedFrameDecoder to see if it helps.

**Comment by Vostan** [comment]
Hi folks,

This issue is quite old I wander if there is some solution to it out there,

E.g. currently we are having similar issue. 
We connect to Jpos iso server and get iso messages in this format (first 4 bytes, the length of message)(MTI)(bit map)(message), currently we just cut the first 4byte so message will be parsed, but this is not correct and in even small load it does not work.

**Comment by kpavlov** [comment]
Is it still valid?

**Comment by Vostan** [comment]
It is resolved already by another ticket. 
https://github.com/kpavlov/jreactive-8583/issues/83
