### ISSUE TITLE
ISO 8583 standard version question

### ISSUE THREAD

**Issue by solnaranu** [kpavlov/jreactive-8583#99]
Is there a specific reason the code below uses message type indicator 0x1644 (specifically, the digit 1), thereby assuming the 1993 version of the ISO 8583 standard, as opposed to the [1987 or 2003 versions](https://en.wikipedia.org/wiki/ISO_8583#Message_type_indicator_(MTI))?

https://github.com/kpavlov/jreactive-8583/blob/c9b180735de5046016af9a22e504199f7ddd69a1/src/main/java/com/github/kpavlov/jreactive8583/netty/pipeline/ParseExceptionHandler.java#L39

**Comment by kpavlov** [comment]
There is no specific reason. Should it be changed to `0x2644` ?

**Comment by solnaranu** [comment]
Only if you want to target the 2003 standard version specifically, but I doubt that since it is not really widely accepted.

Personally, I'm interested in the 1987 standard version and your lib works fine, with the exception of this.

On more thing to consider is that the underlying j8583 lib considers only 128 fields, and that would be the 1987 standard version (1993 has 192 fields).

I guess the simple way would be to use 0x0644. The more involved way would make it configurable.

**Comment by kpavlov** [comment]
Versions can be now customized (#103)
